- hosts: all
  vars_files:
  - vars.yaml

  tasks:
  - name: Tear down existing services
    shell: docker stack rm amigo 
    register: output
    args:
      executable: /bin/bash

  - debug: msg={{ output.stderr.split('\n') }}
    when: output.stderr != "" 
