- hosts: all
  vars_files:
  - vars.yaml

  tasks:
  - name: Create and start services
    shell: docker stack deploy --compose-file {{ stage_dir }}/docker-compose.yaml amigo
    register: output
    args:
      executable: /bin/bash

  - name: Check status
    shell: |
           docker stack ps amigo
    register: output 
    args:
      executable: /bin/bash
    changed_when: False

  - debug: msg={{ output.stdout.split('\n') }}
